name: ESLint

on: push

jobs:
  run-linters:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable ESLint
          eslint: true
          eslint_dir: ./frontend
          eslint__extensions: "js,jsx"