name: Lint

on: push

jobs:
  run-linters:
    name: Google Java Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2 # v2 minimum required

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11" # Recommended: latest versions of Google Java Format require JDK 11+

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: "true"
          args: "--skip-sorting-imports --dry-run --set-exit-if-changed"
          githubToken: ${{ secrets.GITHUB_TOKEN }} # Recommended if you use MacOS

      - name: Run ESLint
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable ESLint
          eslint: true
          eslint_dir: ./frontend
          eslint_extensions: "js,jsx"
